import { Router } from "express";
import authenticationRoutes from "@/resources/v1/authentication/authentication.routes";
import otpsRoutes from "@/resources/v1/otps/otps.routes";
import userRoutes from "@/resources/v1/users/users.routes";
import userWalletsRoutes from "@/resources/v1/user-wallets/user-wallets.routes";
import webhookRoutes from "@/resources/v1/user-wallets/webhook.routes";
import serviceUserConfigurationRoutes from "@/resources/v1/service-user-configuration/service-user-configuration.routes";
import v1ServiceAreaConfigRoutes from "../resources/v1/service-area-configurations/service-area-configurations.routes";
import v1ServiceCountryConfigRoutes from "../resources/v1/service-country-configurations/service-country-configurations.routes";
import v1ServiceDocumentConfigRoutes from "../resources/v1/service-document-configurations/service-document-configurations.routes";
import serviceUserDocumentConfigurationRoutes from "@/resources/v1/service-user-document-configuration/service-user-document-configuration.routes";
import v1BundleCountryConfigRoutes from "../resources/v1/bundle-country-configurations/bundle-country-configurations.routes";
import v1BundleServiceItemRoutes from "../resources/v1/bundle-service-items/bundle-service-items.routes";
import authentication from "@/middlewares/authentication-validation.middleware";
import { authorizationApi } from "@/middlewares/authorization-api.middleware";

const router = Router();
router.use("/authentication", authenticationRoutes);
router.use("/otps", otpsRoutes);
router.use("/users", authentication, authorizationApi, userRoutes);
router.use("/wallets", authentication, authorizationApi, userWalletsRoutes);
router.use("/service-area-configurations", authentication, authorizationApi, v1ServiceAreaConfigRoutes);
router.use("/service-country-configurations", authentication, authorizationApi, v1ServiceCountryConfigRoutes);
router.use("/service-document-configurations", authentication, authorizationApi, v1ServiceDocumentConfigRoutes);
router.use("/service-user-configurations", authentication, authorizationApi, serviceUserConfigurationRoutes);
router.use("/service-user-document-configurations", authentication, authorizationApi, serviceUserDocumentConfigurationRoutes);
router.use("/bundle-country-configurations", authentication, authorizationApi, v1BundleCountryConfigRoutes);
router.use("/bundle-service-items", authentication, authorizationApi, v1BundleServiceItemRoutes);
router.use("/webhooks", webhookRoutes);

export default router;
