import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/authentication-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";

const authenticationApiData = (): IAPI[] => [
  {
    activity_type: activityTypes.Send,
    module: moduleTypes.Authentication,
    activity_name: activityName.SentOtp,
    activity_code: activityCode.SentOtp,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/sent-otp",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "phone",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "country",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "type",
        value: "login",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "device_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "user_type",
        value: "user",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "declaimers",
        value: "array",
        type: datatypes.Array,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: false,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },
  {
    activity_type: activityTypes.Login,
    module: moduleTypes.Authentication,
    activity_name: activityName.VerifyOtp,
    activity_code: activityCode.VerifyOtp,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/verify-otp/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "otp",
        value: "123456",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: false,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },
  {
    activity_type: activityTypes.Refresh,
    module: moduleTypes.Authentication,
    activity_name: activityName.RefreshToken,
    activity_code: activityCode.refreshToken,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/refresh-token",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "refresh_token",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "device_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "device_name",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: false,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },
  {
    activity_type: activityTypes.Login,
    module: moduleTypes.Authentication,
    activity_name: activityName.Login,
    activity_code: activityCode.Login,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/admin-login",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "email",
        value: "admin@example.com",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "password",
        value: "password123",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "device_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "device_name",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: false,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },
  {
    activity_type: activityTypes.Login,
    module: moduleTypes.Authentication,
    activity_name: activityName.Login,
    activity_code: activityCode.Login,
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/login",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "email",
        value: "admin@example.com",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "password",
        value: "password123",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "device_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "device_name",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: false,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },
  {
    activity_type: activityTypes.Logout,
    module: moduleTypes.Authentication,
    activity_name: "Logout",
    activity_code: "logout",
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/logout",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
  },
  {
    activity_type: activityTypes.Logout,
    module: moduleTypes.Authentication,
    activity_name: "Logout All",
    activity_code: "logout_all",
    activity_method: apiMethods.POST,
    url: "/api/v1/authentication/logout-all",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
  },
];

export default authenticationApiData;
