import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import {
  activityCode,
  activityName,
} from "../../activities/bundle-statuses-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";
import { defaultSearchParams } from "../../../../utils/helpers/seeder.helper";

const bundleStatusesApiData = (): IAPI[] => [
  // create bundle status
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.BundleStatuses,
    activity_name: activityName.createBundleStatuses,
    activity_code: activityCode.createBundleStatuses,
    activity_method: apiMethods.POST,
    url: "/api/v1/masters/bundle-statuses",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "title",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "label",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "color",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_default",
        value: "boolean",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // list bundle statuses
  {
    activity_type: activityTypes.List,
    module: moduleTypes.BundleStatuses,
    activity_name: activityName.listBundleStatuses,
    activity_code: activityCode.listBundleStatuses,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundle-statuses",
    status: true,
    form_params: [],
    search_params: [
      ...defaultSearchParams,
      {
        title: "title_like",
        value: "title",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        is_required: false,
      },
      {
        title: "label",
        value: "label",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
    ],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"),
    getRoleId("user"), getRoleId("employee")],
  },
  // show bundle status
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.BundleStatuses,
    activity_name: activityName.showBundleStatuses,
    activity_code: activityCode.showBundleStatuses,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundle-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // update bundle status
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleStatuses,
    activity_name: activityName.updateBundleStatuses,
    activity_code: activityCode.updateBundleStatuses,
    activity_method: apiMethods.PUT,
    url: "/api/v1/masters/bundle-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "title",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "label",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "color",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_default",
        value: "boolean",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // delete bundle status
  {
    activity_type: activityTypes.Delete,
    module: moduleTypes.BundleStatuses,
    activity_name: activityName.deleteBundleStatuses,
    activity_code: activityCode.deleteBundleStatuses,
    activity_method: apiMethods.DELETE,
    url: "/api/v1/masters/bundle-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // activate bundle status
  {
    activity_type: activityTypes.Activate,
    module: moduleTypes.BundleStatuses,
    activity_name: activityName.activateBundleStatuses,
    activity_code: activityCode.activateBundleStatuses,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundle-statuses/:id/enable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // deactivate bundle status
  {
    activity_type: activityTypes.Deactivate,
    module: moduleTypes.BundleStatuses,
    activity_name: activityName.deactivateBundleStatuses,
    activity_code: activityCode.deactivateBundleStatuses,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundle-statuses/:id/disable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
];

export default bundleStatusesApiData;
