import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import {
  activityCode,
  activityName,
} from "../../activities/bundle-country-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";

const bundleCountryApiData = (): IAPI[] => [
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.BundleCountryConfigurations,
    activity_name: activityName.createBundleCountry,
    activity_code: activityCode.createBundleCountry,
    activity_method: apiMethods.POST,
    url: "/api/v1/bundle-country-configurations",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "bundle_id",
        value: "64b8a1c8f1e67290bc5b4d1a",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "country_id",
        value: "64b8a1c8f1e67290bc5b4d1b",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency_id",
        value: "64b8a1c8f1e67290bc5b4d1c",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "unit_id",
        value: "64b8a1c8f1e67290bc5b4d1d",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_callout_bundle",
        value: "false",
        type: datatypes.Boolean,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_fixed_price",
        value: "true",
        type: datatypes.Boolean,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "price",
        value: "100",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "call_out_fee",
        value: "50",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "minimum_price",
        value: "20",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "maximum_price",
        value: "150",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "estimated_time",
        value: "60",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "estimated_time_unit",
        value: "minute",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "individual_services_total",
        value: "200",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "bundle_discount_type",
        value: "FIXED",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "bundle_discount_value",
        value: "20",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.BundleCountryConfigurations,
    activity_name: activityName.listBundleCountry,
    activity_code: activityCode.listBundleCountry,
    activity_method: apiMethods.GET,
    url: "/api/v1/bundle-country-configurations",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.BundleCountryConfigurations,
    activity_name: activityName.showBundleCountry,
    activity_code: activityCode.showBundleCountry,
    activity_method: apiMethods.GET,
    url: "/api/v1/bundle-country-configurations/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleCountryConfigurations,
    activity_name: activityName.updateBundleCountry,
    activity_code: activityCode.updateBundleCountry,
    activity_method: apiMethods.PUT,
    url: "/api/v1/bundle-country-configurations/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "price",
        value: "120",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_callout_bundle",
        value: "false",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_fixed_price",
        value: "true",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "call_out_fee",
        value: "50",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "minimum_price",
        value: "20",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "maximum_price",
        value: "150",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Delete,
    module: moduleTypes.BundleCountryConfigurations,
    activity_name: activityName.deleteBundleCountry,
    activity_code: activityCode.deleteBundleCountry,
    activity_method: apiMethods.DELETE,
    url: "/api/v1/bundle-country-configurations/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
];

export default bundleCountryApiData;
