import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import {
  activityCode,
  activityName,
} from "../../activities/bundle-area-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";

const bundleAreaApiData = (): IAPI[] => [
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.BundleAreaConfigurations,
    activity_name: activityName.createBundleArea,
    activity_code: activityCode.createBundleArea,
    activity_method: apiMethods.POST,
    url: "/api/v1/bundle-area-configurations",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "country_configuration_id",
        value: "64b8a1c8f1e67290bc5b4d1a",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "suburb_ids",
        value: '["64b8a1c8f1e67290bc5b4d1b", "64b8a1c8f1e67290bc5b4d1c"]',
        type: datatypes.Array,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.BundleAreaConfigurations,
    activity_name: activityName.listBundleArea,
    activity_code: activityCode.listBundleArea,
    activity_method: apiMethods.GET,
    url: "/api/v1/bundle-area-configurations",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },

  {
    activity_type: activityTypes.Show,
    module: moduleTypes.BundleAreaConfigurations,
    activity_name: activityName.showBundleArea,
    activity_code: activityCode.showBundleArea,
    activity_method: apiMethods.GET,
    url: "/api/v1/bundle-area-configurations/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleAreaConfigurations,
    activity_name: activityName.updateBundleArea,
    activity_code: activityCode.updateBundleArea,
    activity_method: apiMethods.PUT,
    url: "/api/v1/bundle-area-configurations/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "price",
        value: "1200",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_callout_bundle",
        value: "false",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_fixed_price",
        value: "true",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "call_out_fee",
        value: "50",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "minimum_price",
        value: "200",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "maximum_price",
        value: "2500",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "estimated_time",
        value: "2",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "estimated_time_unit",
        value: "hours",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "individual_services_total",
        value: "1500",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "bundle_discount_type",
        value: "FIXED",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "bundle_discount_value",
        value: "300",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "unit_id",
        value: "64b8a1c8f1e67290bc5b4d1a",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency_id",
        value: "64b8a1c8f1e67290bc5b4d1b",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_active",
        value: "true",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleAreaConfigurations,
    activity_name: activityName.enableBundleArea,
    activity_code: activityCode.enableBundleArea,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/bundle-area-configurations/:id/enable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleAreaConfigurations,
    activity_name: activityName.disableBundleArea,
    activity_code: activityCode.disableBundleArea,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/bundle-area-configurations/:id/disable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
];

export default bundleAreaApiData;
