import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import {
  activityCode,
  activityName,
} from "../../activities/bundle-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";
import { defaultSearchParams } from "../../../../utils/helpers/seeder.helper";

const bundleApiData = (): IAPI[] => [
  // create bundle
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Bundles,
    activity_name: activityName.createBundle,
    activity_code: activityCode.createBundle,
    activity_method: apiMethods.POST,
    url: "/api/v1/masters/bundles",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "name",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "display_name",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "code",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "description",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "icon",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "status_id",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "sort_order",
        value: "number",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "tags",
        value: "array",
        type: datatypes.Array,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "metadata",
        value: "object",
        type: datatypes.Object,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // list bundles
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Bundles,
    activity_name: activityName.listBundles,
    activity_code: activityCode.listBundles,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundles",
    status: true,
    form_params: [],
    search_params: [
      ...defaultSearchParams,
      {
        title: "name_like",
        value: "name",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        is_required: false,
      },
      {
        title: "code",
        value: "code",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
      {
        title: "status_id",
        value: "status_id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
      {
        title: "is_active",
        value: "is_active",
        allowed_values: [],
        datatype: datatypes.Boolean,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
    ],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  // show bundle
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Bundles,
    activity_name: activityName.showBundle,
    activity_code: activityCode.showBundle,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundles/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // update bundle
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.Bundles,
    activity_name: activityName.updateBundle,
    activity_code: activityCode.updateBundle,
    activity_method: apiMethods.PUT,
    url: "/api/v1/masters/bundles/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "name",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "display_name",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "code",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "description",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "icon",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "status_id",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "sort_order",
        value: "number",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "tags",
        value: "array",
        type: datatypes.Array,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "metadata",
        value: "object",
        type: datatypes.Object,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // delete bundle
  {
    activity_type: activityTypes.Delete,
    module: moduleTypes.Bundles,
    activity_name: activityName.deleteBundle,
    activity_code: activityCode.deleteBundle,
    activity_method: apiMethods.DELETE,
    url: "/api/v1/masters/bundles/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // activate bundle
  {
    activity_type: activityTypes.Activate,
    module: moduleTypes.Bundles,
    activity_name: activityName.activateBundle,
    activity_code: activityCode.activateBundle,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundles/:id/enable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // deactivate bundle
  {
    activity_type: activityTypes.Deactivate,
    module: moduleTypes.Bundles,
    activity_name: activityName.deactivateBundle,
    activity_code: activityCode.deactivateBundle,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundles/:id/disable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
];

export default bundleApiData;
