import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import {
  activityCode,
  activityName,
} from "../../activities/bundle-user-mapping-status-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";
import { defaultSearchParams } from "../../../../utils/helpers/seeder.helper";

const bundleUserMappingStatusApiData = (): IAPI[] => [
  // create bundle user mapping status
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.BundleUserMappingStatuses,
    activity_name: activityName.createBundleUserMappingStatus,
    activity_code: activityCode.createBundleUserMappingStatus,
    activity_method: apiMethods.POST,
    url: "/api/v1/masters/bundle-user-mapping-statuses",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "title",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "label",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "color",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_default",
        value: "boolean",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // list bundle user mapping statuses
  {
    activity_type: activityTypes.List,
    module: moduleTypes.BundleUserMappingStatuses,
    activity_name: activityName.listBundleUserMappingStatus,
    activity_code: activityCode.listBundleUserMappingStatus,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundle-user-mapping-statuses",
    status: true,
    form_params: [],
    search_params: [
      ...defaultSearchParams,
      {
        title: "title_like",
        value: "title",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        is_required: false,
      },
      {
        title: "label",
        value: "label",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
    ],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // show bundle user mapping status
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.BundleUserMappingStatuses,
    activity_name: activityName.showBundleUserMappingStatus,
    activity_code: activityCode.showBundleUserMappingStatus,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundle-user-mapping-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // update bundle user mapping status
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleUserMappingStatuses,
    activity_name: activityName.updateBundleUserMappingStatus,
    activity_code: activityCode.updateBundleUserMappingStatus,
    activity_method: apiMethods.PUT,
    url: "/api/v1/masters/bundle-user-mapping-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "title",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "label",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "color",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_default",
        value: "boolean",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // delete bundle user mapping status
  {
    activity_type: activityTypes.Delete,
    module: moduleTypes.BundleUserMappingStatuses,
    activity_name: activityName.deleteBundleUserMappingStatus,
    activity_code: activityCode.deleteBundleUserMappingStatus,
    activity_method: apiMethods.DELETE,
    url: "/api/v1/masters/bundle-user-mapping-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // activate bundle user mapping status
  {
    activity_type: activityTypes.Activate,
    module: moduleTypes.BundleUserMappingStatuses,
    activity_name: activityName.activateBundleUserMappingStatus,
    activity_code: activityCode.activateBundleUserMappingStatus,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundle-user-mapping-statuses/:id/enable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // deactivate bundle user mapping status
  {
    activity_type: activityTypes.Deactivate,
    module: moduleTypes.BundleUserMappingStatuses,
    activity_name: activityName.deactivateBundleUserMappingStatus,
    activity_code: activityCode.deactivateBundleUserMappingStatus,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundle-user-mapping-statuses/:id/disable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
];

export default bundleUserMappingStatusApiData;
