import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import {
  activityCode,
  activityName,
} from "../../activities/bundle-location-config-statuses-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";
import { defaultSearchParams } from "../../../../utils/helpers/seeder.helper";

const bundleLocationConfigStatusesApiData = (): IAPI[] => [
  // create bundle location config status
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.BundleLocationConfigStatuses,
    activity_name: activityName.createBundleLocationConfigStatuses,
    activity_code: activityCode.createBundleLocationConfigStatuses,
    activity_method: apiMethods.POST,
    url: "/api/v1/masters/bundle-location-config-statuses",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "title",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "label",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "color",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_default",
        value: "boolean",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // list bundle location config statuses
  {
    activity_type: activityTypes.List,
    module: moduleTypes.BundleLocationConfigStatuses,
    activity_name: activityName.listBundleLocationConfigStatuses,
    activity_code: activityCode.listBundleLocationConfigStatuses,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundle-location-config-statuses",
    status: true,
    form_params: [],
    search_params: [
      ...defaultSearchParams,
      {
        title: "title_like",
        value: "title",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Partial,
        is_active: true,
        is_required: false,
      },
      {
        title: "label",
        value: "label",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
    ],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  // show bundle location config status
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.BundleLocationConfigStatuses,
    activity_name: activityName.showBundleLocationConfigStatuses,
    activity_code: activityCode.showBundleLocationConfigStatuses,
    activity_method: apiMethods.GET,
    url: "/api/v1/masters/bundle-location-config-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  // update bundle location config status
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleLocationConfigStatuses,
    activity_name: activityName.updateBundleLocationConfigStatuses,
    activity_code: activityCode.updateBundleLocationConfigStatuses,
    activity_method: apiMethods.PUT,
    url: "/api/v1/masters/bundle-location-config-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "title",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "label",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "color",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_default",
        value: "boolean",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // delete bundle location config status
  {
    activity_type: activityTypes.Delete,
    module: moduleTypes.BundleLocationConfigStatuses,
    activity_name: activityName.deleteBundleLocationConfigStatuses,
    activity_code: activityCode.deleteBundleLocationConfigStatuses,
    activity_method: apiMethods.DELETE,
    url: "/api/v1/masters/bundle-location-config-statuses/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // activate bundle location config status
  {
    activity_type: activityTypes.Activate,
    module: moduleTypes.BundleLocationConfigStatuses,
    activity_name: activityName.activateBundleLocationConfigStatuses,
    activity_code: activityCode.activateBundleLocationConfigStatuses,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundle-location-config-statuses/:id/enable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
  // deactivate bundle location config status
  {
    activity_type: activityTypes.Deactivate,
    module: moduleTypes.BundleLocationConfigStatuses,
    activity_name: activityName.deactivateBundleLocationConfigStatuses,
    activity_code: activityCode.deactivateBundleLocationConfigStatuses,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/masters/bundle-location-config-statuses/:id/disable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin")],
  },
];

export default bundleLocationConfigStatusesApiData;
