import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import {
  activityCode,
  activityName,
} from "../../activities/bundle-service-items-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";

const bundleServiceItemsApiData = (): IAPI[] => [
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.BundleServiceItems,
    activity_name: activityName.createBundleServiceItem,
    activity_code: activityCode.createBundleServiceItem,
    activity_method: apiMethods.POST,
    url: "/api/v1/bundle-service-items",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "bundle_id",
        value: "64b8a1c8f1e67290bc5b4d1a",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "service_id",
        value: "64b8a1c8f1e67290bc5b4d1b",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "sort_order",
        value: "0",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "quantity",
        value: "1",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_mandatory",
        value: "true",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_included",
        value: "true",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.BundleServiceItems,
    activity_name: activityName.listBundleServiceItem,
    activity_code: activityCode.listBundleServiceItem,
    activity_method: apiMethods.GET,
    url: "/api/v1/bundle-service-items",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.BundleServiceItems,
    activity_name: activityName.showBundleServiceItem,
    activity_code: activityCode.showBundleServiceItem,
    activity_method: apiMethods.GET,
    url: "/api/v1/bundle-service-items/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleServiceItems,
    activity_name: activityName.updateBundleServiceItem,
    activity_code: activityCode.updateBundleServiceItem,
    activity_method: apiMethods.PUT,
    url: "/api/v1/bundle-service-items/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "sort_order",
        value: "1",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "quantity",
        value: "2",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_mandatory",
        value: "true",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "is_included",
        value: "true",
        type: datatypes.Boolean,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.BundleServiceItems,
    activity_name: activityName.toggleStatusBundleServiceItem,
    activity_code: activityCode.toggleStatusBundleServiceItem,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/bundle-service-items/:id/status",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "is_active",
        value: "false",
        type: datatypes.Boolean,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
  {
    activity_type: activityTypes.Delete,
    module: moduleTypes.BundleServiceItems,
    activity_name: activityName.deleteBundleServiceItem,
    activity_code: activityCode.deleteBundleServiceItem,
    activity_method: apiMethods.DELETE,
    url: "/api/v1/bundle-service-items/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },
];

export default bundleServiceItemsApiData;
