import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/carousel-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";
import { defaultSearchParams } from "../../../../utils/helpers/seeder.helper";

const carouselsApiData = (): IAPI[] => [
    // Create Carousel
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Carousels,
        activity_name: activityName.createCarousel,
        activity_code: activityCode.createCarousel,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/carousels",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "slideType",
                value: "promotion",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "title",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "description",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "image",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "target",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "button",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "colorPattern",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "redeemCode",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // List Carousels
    {
        activity_type: activityTypes.List,
        module: moduleTypes.Carousels,
        activity_name: activityName.listCarousel,
        activity_code: activityCode.listCarousel,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/carousels",
        status: true,
        form_params: [],
        search_params: [
            ...defaultSearchParams,
            {
                title: "slideType",
                value: "slideType",
                allowed_values: ["promotion", "coupon", "info", "announcement", "banner", "news"],
                datatype: datatypes.String,
                search_type: searchTypes.Exact,
                is_active: true,
            },
            {
                title: "title_like",
                value: "title",
                allowed_values: [],
                datatype: datatypes.String,
                search_type: searchTypes.Partial,
                is_active: true,
            },
        ],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
    },

    // Show Carousel
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.Carousels,
        activity_name: activityName.showCarousel,
        activity_code: activityCode.showCarousel,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/carousels/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
    },

    // Update Carousel
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Carousels,
        activity_name: activityName.updateCarousel,
        activity_code: activityCode.updateCarousel,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/carousels/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "slideType",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "title",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "description",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "image",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "target",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "button",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "colorPattern",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "redeemCode",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // Delete Carousel
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.Carousels,
        activity_name: activityName.deleteCarousel,
        activity_code: activityCode.deleteCarousel,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/carousels/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // Activate Carousel
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Carousels,
        activity_name: activityName.activateCarousel,
        activity_code: activityCode.activateCarousel,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/carousels/:id/enable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // Deactivate Carousel
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Carousels,
        activity_name: activityName.deactivateCarousel,
        activity_code: activityCode.deactivateCarousel,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/carousels/:id/disable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
];

export default carouselsApiData;
