import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/currency-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";

const currenciesApiData = (): IAPI[] => [
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Currencies,
        activity_name: activityName.createCurrency,
        activity_code: activityCode.createCurrency,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/currencies",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.List,
        module: moduleTypes.Currencies,
        activity_name: activityName.listCurrency,
        activity_code: activityCode.listCurrency,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/currencies",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.Currencies,
        activity_name: activityName.showCurrency,
        activity_code: activityCode.showCurrency,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/currencies/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Currencies,
        activity_name: activityName.updateCurrency,
        activity_code: activityCode.updateCurrency,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/currencies/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.Currencies,
        activity_name: activityName.deleteCurrency,
        activity_code: activityCode.deleteCurrency,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/currencies/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
];

export default currenciesApiData;
