import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/enablement-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";

const enablementApiData = (): IAPI[] => [
  // 1. List Conditions Metadata
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Enablement,
    activity_name: activityName.listConditions,
    activity_code: activityCode.listConditions,
    activity_method: apiMethods.GET,
    url: "/api/v1/enablement/conditions",
    status: true,
    form_params: [],
    search_params: [
      {
        title: "entityType",
        value: "entityType",
        allowed_values: ["COUNTRY", "REGION", "PROVIDER"],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
    ],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },

  // 2. Get Audits
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Enablement,
    activity_name: activityName.getAudits,
    activity_code: activityCode.getAudits,
    activity_method: apiMethods.GET,
    url: "/api/v1/enablement/audits",
    status: true,
    form_params: [],
    search_params: [
      {
        title: "policyId",
        value: "policyId",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
      {
        title: "entityType",
        value: "entityType",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
        is_required: false,
      },
    ],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },

  // 3. Get Policies by Entity Type
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Enablement,
    activity_name: activityName.getPolicies,
    activity_code: activityCode.getPolicies,
    activity_method: apiMethods.GET,
    url: "/api/v1/enablement/policies/:entityType",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },

  // 4. Get Policy by Entity Type and Version
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Enablement,
    activity_name: activityName.getPolicyById,
    activity_code: activityCode.getPolicyById,
    activity_method: apiMethods.GET,
    url: "/api/v1/enablement/policies/:entityType/:version",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },

  // 5. Get Policy by ID
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Enablement,
    activity_name: activityName.getPolicyById,
    activity_code: activityCode.getPolicyById,
    activity_method: apiMethods.GET,
    url: "/api/v1/enablement/policy/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },

  // 6. Create Policy Draft
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Enablement,
    activity_name: activityName.createPolicy,
    activity_code: activityCode.createPolicy,
    activity_method: apiMethods.POST,
    url: "/api/v1/enablement/policies",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "entity_type",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "name",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "description",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "rules",
        value: "object",
        type: datatypes.Object,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "effective_from",
        value: "date",
        type: datatypes.Date,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "effective_until",
        value: "date",
        type: datatypes.Date,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },

  // 7. Update Policy Draft
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.Enablement,
    activity_name: activityName.updatePolicy,
    activity_code: activityCode.updatePolicy,
    activity_method: apiMethods.PUT,
    url: "/api/v1/enablement/policies/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "name",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "description",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "rules",
        value: "object",
        type: datatypes.Object,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "effective_from",
        value: "date",
        type: datatypes.Date,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "effective_until",
        value: "date",
        type: datatypes.Date,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },

  // 8. Validate Policy
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Enablement,
    activity_name: activityName.validatePolicy,
    activity_code: activityCode.validatePolicy,
    activity_method: apiMethods.POST,
    url: "/api/v1/enablement/policies/:id/validate",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "rules",
        value: "object",
        type: datatypes.Object,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },

  // 9. Publish Policy
  {
    activity_type: activityTypes.Activate,
    module: moduleTypes.Enablement,
    activity_name: activityName.publishPolicy,
    activity_code: activityCode.publishPolicy,
    activity_method: apiMethods.POST,
    url: "/api/v1/enablement/policies/:id/publish",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },

  // 10. Rollback Policy
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.Enablement,
    activity_name: activityName.rollbackPolicy,
    activity_code: activityCode.rollbackPolicy,
    activity_method: apiMethods.POST,
    url: "/api/v1/enablement/policies/:id/rollback",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin")],
  },

  // 11. Evaluate Entity Enablement
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Enablement,
    activity_name: activityName.evaluateEntity,
    activity_code: activityCode.evaluateEntity,
    activity_method: apiMethods.POST,
    url: "/api/v1/enablement/policies/:entityType/evaluate/:entityId",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
  },
];

export default enablementApiData;
