import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/provider-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";
import { defaultSearchParams } from "../../../../utils/helpers/seeder.helper";

const providerApiData = (): IAPI[] => [
    // create provider
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Providers,
        activity_name: activityName.createProvider,
        activity_code: activityCode.createProvider,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/providers",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [
            {
                key: "name",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "supportedCountries",
                value: "array",
                type: datatypes.Array,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // list provider
    {
        activity_type: activityTypes.List,
        module: moduleTypes.Providers,
        activity_name: activityName.listProvider,
        activity_code: activityCode.listProvider,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/providers",
        status: true,
        form_params: [],
        search_params: [
            ...defaultSearchParams,
            {
                title: "name_like",
                value: "name",
                allowed_values: [],
                datatype: datatypes.String,
                search_type: searchTypes.Partial,
                is_active: true,
            },
        ],

        access_params: {
        },

        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: true,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
    },

    // update provider
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Providers,
        activity_name: activityName.updateProvider,
        activity_code: activityCode.updateProvider,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/providers/:id",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [
            {
                key: "name",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "supportedCountries",
                value: "array",
                type: datatypes.Array,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // delete provider
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.Providers,
        activity_name: activityName.deleteProvider,
        activity_code: activityCode.deleteProvider,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/providers/:id",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // activate provider
    {
        activity_type: activityTypes.Activate,
        module: moduleTypes.Providers,
        activity_name: activityName.activateProvider,
        activity_code: activityCode.activateProvider,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/providers/:id/enable",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // deactivate provider
    {
        activity_type: activityTypes.Deactivate,
        module: moduleTypes.Providers,
        activity_name: activityName.deactivateProvider,
        activity_code: activityCode.deactivateProvider,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/providers/:id/disable",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // show provider
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.Providers,
        activity_name: activityName.showProvider,
        activity_code: activityCode.showProvider,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/providers/:id",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: true,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
    },

    // log provider
    {
        activity_type: activityTypes.Log,
        module: moduleTypes.Providers,
        activity_name: activityName.logProvider,
        activity_code: activityCode.logProvider,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/providers/log",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // link country to provider
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Providers,
        activity_name: activityName.linkCountryProvider,
        activity_code: activityCode.linkCountryProvider,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/providers/:id/link-countries/:id",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [
            {
                key: "config",
                value: "object",
                type: datatypes.Object,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "apiKey",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "apiSecret",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "authToken",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "senderId",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "username",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "password",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "baseUrl",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "apiVersion",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "additionalConfig",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "type",
                value: "array",
                type: datatypes.Array,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "name",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: true,
                parent_key: "type",
            },
            {
                key: "description",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: true,
                parent_key: "type",
            },
            {
                key: "payloadSchema",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: true,
                parent_key: "type",
            },
            {
                key: "phone",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "message",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "templateId",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "variables",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "email",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "to",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "subject",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "body",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "supportFrom",
                value: "date",
                type: datatypes.Date,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "supportUntil",
                value: "date",
                type: datatypes.Date,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // update link country of provider
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Providers,
        activity_name: activityName.updateLinkCountryProvider,
        activity_code: activityCode.updateLinkCountryProvider,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/providers/:id/link-countries/:id",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [
            {
                key: "config",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "apiKey",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "apiSecret",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "authToken",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "senderId",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "username",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "password",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "baseUrl",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "apiVersion",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "additionalConfig",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: true,
                parent_key: "config",
            },
            {
                key: "type",
                value: "array",
                type: datatypes.Array,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "name",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: true,
                parent_key: "type",
            },
            {
                key: "description",
                value: "string",
                type: datatypes.String,
                required: true,
                parent: true,
                parent_key: "type",
            },
            {
                key: "payloadSchema",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: true,
                parent_key: "type",
            },
            {
                key: "phone",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "message",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "templateId",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "variables",
                value: "object",
                type: datatypes.Object,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "email",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "to",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "subject",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "body",
                value: "string",
                type: datatypes.String,
                required: false,
                parent: true,
                parent_key: "payloadSchema",
            },
            {
                key: "supportFrom",
                value: "date",
                type: datatypes.Date,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "supportUntil",
                value: "date",
                type: datatypes.Date,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },

    // test provider type
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Providers,
        activity_name: activityName.testProviderType,
        activity_code: activityCode.testProviderType,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/providers/:id/link-countries/:id/types/:id/test",
        status: true,
        form_params: [],
        search_params: [],

        access_params: {
        },

        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
];

export default providerApiData;
