import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/service-country-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";

const serviceCountryApiData = (): IAPI[] => [
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.ServiceCountryConfigurations,
        activity_name: activityName.createServiceCountry,
        activity_code: activityCode.createServiceCountry,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/service-country-configurations",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "service_id",
                value: "64b8a1c8f1e67290bc5b4d1a",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "country_id",
                value: "64b8a1c8f1e67290bc5b4d1b",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "currency_id",
                value: "64b8a1c8f1e67290bc5b4d1c",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "unit_id",
                value: "64b8a1c8f1e67290bc5b4d1d",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "required_licenses",
                value: "true",
                type: datatypes.Boolean,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "is_callout_service",
                value: "false",
                type: datatypes.Boolean,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "is_fixed_price",
                value: "true",
                type: datatypes.Boolean,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "price",
                value: "100",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "call_out_fee",
                value: "50",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "minimum_unit_price",
                value: "20",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "maximum_unit_price",
                value: "150",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "estimated_time",
                value: "60",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "estimated_time_unit",
                value: "minute",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.List,
        module: moduleTypes.ServiceCountryConfigurations,
        activity_name: activityName.listServiceCountry,
        activity_code: activityCode.listServiceCountry,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/service-country-configurations",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.ServiceCountryConfigurations,
        activity_name: activityName.showServiceCountry,
        activity_code: activityCode.showServiceCountry,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/service-country-configurations/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.ServiceCountryConfigurations,
        activity_name: activityName.updateServiceCountry,
        activity_code: activityCode.updateServiceCountry,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/service-country-configurations/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "price",
                value: "120",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "required_licenses",
                value: "true",
                type: datatypes.Boolean,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "is_callout_service",
                value: "false",
                type: datatypes.Boolean,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "is_fixed_price",
                value: "true",
                type: datatypes.Boolean,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "call_out_fee",
                value: "50",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "minimum_unit_price",
                value: "20",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "maximum_unit_price",
                value: "150",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.ServiceCountryConfigurations,
        activity_name: activityName.deleteServiceCountry,
        activity_code: activityCode.deleteServiceCountry,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/service-country-configurations/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
];

export default serviceCountryApiData;
