import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/service-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { searchTypes } from "@/utils/definitions/constants/search-types";

const servicesApiData = (): IAPI[] => [
    /* --- Categories --- */
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Services,
        activity_name: activityName.createCategory,
        activity_code: activityCode.createCategory,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/services/category",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "name",
                value: "Home Services",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "description",
                value: "Category for all home services",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "icon",
                value: "64b8a1c8f1e67290bc5b4d1a",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    /* --- Subcategories --- */
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Services,
        activity_name: activityName.createSubCategory,
        activity_code: activityCode.createSubCategory,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/services/sub-category",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "parent_id",
                value: "64b8a1c8f1e67290bc5b4d1a",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "name",
                value: "Plumbing",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "description",
                value: "All plumbing related services",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "icon",
                value: "64b8a1c8f1e67290bc5b4d1a",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    /* --- Services / Tasks --- */
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Services,
        activity_name: activityName.createService,
        activity_code: activityCode.createService,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/services/service",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "parent_id",
                value: "64b8a1c8f1e67290bc5b4d1a",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "name",
                value: "Pipe Leak Repair",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "description",
                value: "Fixing leaking pipes and fittings",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "icon",
                value: "64b8a1c8f1e67290bc5b4d1a",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "estimated_time",
                value: "60",
                type: datatypes.Number,
                required: true,
                parent: false,
                parent_key: "",
            },
            {
                key: "estimated_time_unit",
                value: "minute",
                type: datatypes.String,
                required: true,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    /* --- Common/Generic Routes --- */
    {
        activity_type: activityTypes.List,
        module: moduleTypes.Services,
        activity_name: activityName.listCategory,
        activity_code: activityCode.listCategory,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/services",
        status: true,
        form_params: [],
        search_params: [
            {
                title: "show_inactive_categories",
                value: "true",
                allowed_values: ["true", "false"],
                datatype: datatypes.Boolean,
                search_type: searchTypes.Exact,
                is_active: true,
                is_required: true,
            },
            {
                title: "show_inactive_subcategories",
                value: "true",
                allowed_values: ["true", "false"],
                datatype: datatypes.Boolean,
                search_type: searchTypes.Exact,
                is_active: true,
                is_required: true,
            },
            {
                title: "show_inactive_services",
                value: "true",
                allowed_values: ["true", "false"],
                datatype: datatypes.Boolean,
                is_active: true,
                is_required: true,
                search_type: searchTypes.Exact,
            },
            {
                title: "remove_empty_categories",
                value: "true",
                allowed_values: ["true", "false"],
                datatype: datatypes.Boolean,
                is_active: true,
                is_required: true,
                search_type: searchTypes.Exact,
            },
            {
                title: "remove_empty_sub_category",
                value: "true",
                allowed_values: ["true", "false"],
                datatype: datatypes.Boolean,
                is_active: true,
                is_required: true,
                search_type: searchTypes.Exact,
            },
            {
                title: "show_only_category",
                value: "false",
                allowed_values: ["true", "false"],
                datatype: datatypes.Boolean,
                is_active: true,
                is_required: true,
                search_type: searchTypes.Exact,
            },
        ],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.Services,
        activity_name: activityName.showService,
        activity_code: activityCode.showService,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/services/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.Services,
        activity_name: activityName.deleteService,
        activity_code: activityCode.deleteService,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/services/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Services,
        activity_name: activityName.activateService,
        activity_code: activityCode.activateService,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/services/:id/enable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Services,
        activity_name: activityName.deactivateService,
        activity_code: activityCode.deactivateService,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/services/:id/disable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Services,
        activity_name: activityName.updateService,
        activity_code: activityCode.updateService,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/services/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {},
        control_params: [],
        payload_params: [
            {
                key: "name",
                value: "Updated Service Name",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "description",
                value: "Updated description",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "icon",
                value: "64b8a1c8f1e67290bc5b4d1a",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "estimated_time",
                value: "45",
                type: datatypes.Number,
                required: false,
                parent: false,
                parent_key: "",
            },
            {
                key: "estimated_time_unit",
                value: "minute",
                type: datatypes.String,
                required: false,
                parent: false,
                parent_key: "",
            },
        ],
        required_authentication: true,
        access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
];

export default servicesApiData;
