import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/service-user-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";

const serviceUserConfigurationApiData = (): IAPI[] => [
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.ServiceUserConfigurations,
    activity_name: activityName.bulkStoreServiceUserConfig,
    activity_code: activityCode.bulkStoreServiceUserConfig,
    activity_method: apiMethods.POST,
    url: "/api/v1/service-user-configurations",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.ServiceUserConfigurations,
    activity_name: activityName.createSingleServiceUserConfig,
    activity_code: activityCode.createSingleServiceUserConfig,
    activity_method: apiMethods.POST,
    url: "/api/v1/service-user-configurations/single",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.ServiceUserConfigurations,
    activity_name: activityName.listServiceUserConfigs,
    activity_code: activityCode.listServiceUserConfigs,
    activity_method: apiMethods.GET,
    url: "/api/v1/service-user-configurations",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.ServiceUserConfigurations,
    activity_name: activityName.showServiceUserConfig,
    activity_code: activityCode.showServiceUserConfig,
    activity_method: apiMethods.GET,
    url: "/api/v1/service-user-configurations/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.ServiceUserConfigurations,
    activity_name: activityName.enableServiceUserConfig,
    activity_code: activityCode.enableServiceUserConfig,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/service-user-configurations/:id/enable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.ServiceUserConfigurations,
    activity_name: activityName.disableServiceUserConfig,
    activity_code: activityCode.disableServiceUserConfig,
    activity_method: apiMethods.PATCH,
    url: "/api/v1/service-user-configurations/:id/disable",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
  {
    activity_type: activityTypes.Delete,
    module: moduleTypes.ServiceUserConfigurations,
    activity_name: activityName.deleteServiceUserConfig,
    activity_code: activityCode.deleteServiceUserConfig,
    activity_method: apiMethods.DELETE,
    url: "/api/v1/service-user-configurations/:id",
    status: true,
    form_params: [],
    search_params: [],
    access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [
      getRoleId("super_admin"),
      getRoleId("admin"),
      getRoleId("user"),
      getRoleId("employee"),
    ],
  },
];

export default serviceUserConfigurationApiData;
