import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/service-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";

const servicesApiData = (): IAPI[] => [
    /* --- Categories --- */
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Services,
        activity_name: activityName.createCategory,
        activity_code: activityCode.createCategory,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/services/category",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    /* --- Subcategories --- */
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Services,
        activity_name: activityName.createSubCategory,
        activity_code: activityCode.createSubCategory,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/services/sub-category",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    /* --- Services / Tasks --- */
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Services,
        activity_name: activityName.createService,
        activity_code: activityCode.createService,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/services/service",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    /* --- Common/Generic Routes --- */
    {
        activity_type: activityTypes.List,
        module: moduleTypes.Services,
        activity_name: activityName.listCategory,
        activity_code: activityCode.listCategory,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/services",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.Services,
        activity_name: activityName.showService,
        activity_code: activityCode.showService,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/services/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.Services,
        activity_name: activityName.deleteService,
        activity_code: activityCode.deleteService,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/services/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Services,
        activity_name: activityName.activateService,
        activity_code: activityCode.activateService,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/services/:id/enable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Services,
        activity_name: activityName.deactivateService,
        activity_code: activityCode.deactivateService,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/services/:id/disable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Services,
        activity_name: activityName.updateService,
        activity_code: activityCode.updateService,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/services/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: false,
      access_roles: [getRoleId("super_admin"), getRoleId("admin")],
    },
];

export default servicesApiData;
