import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { AccessType, IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/statues-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";

const statusesApiData = (): IAPI[] => [
    {
        activity_type: activityTypes.Create,
        module: moduleTypes.Statuses,
        activity_name: activityName.createStatus,
        activity_code: activityCode.createStatus,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/statuses",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.List,
        module: moduleTypes.Statuses,
        activity_name: activityName.listStatus,
        activity_code: activityCode.listStatus,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/statuses",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: true,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Update,
        module: moduleTypes.Statuses,
        activity_name: activityName.updateStatus,
        activity_code: activityCode.updateStatus,
        activity_method: apiMethods.PUT,
        url: "/api/v1/masters/statuses/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Delete,
        module: moduleTypes.Statuses,
        activity_name: activityName.deleteStatus,
        activity_code: activityCode.deleteStatus,
        activity_method: apiMethods.DELETE,
        url: "/api/v1/masters/statuses/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Activate,
        module: moduleTypes.Statuses,
        activity_name: activityName.activateStatus,
        activity_code: activityCode.activateStatus,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/statuses/:id/enable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Deactivate,
        module: moduleTypes.Statuses,
        activity_name: activityName.deactivateStatus,
        activity_code: activityCode.deactivateStatus,
        activity_method: apiMethods.PATCH,
        url: "/api/v1/masters/statuses/:id/disable",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Show,
        module: moduleTypes.Statuses,
        activity_name: activityName.showStatus,
        activity_code: activityCode.showStatus,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/statuses/:id",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: true,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Import,
        module: moduleTypes.Statuses,
        activity_name: activityName.importStatus,
        activity_code: activityCode.importStatus,
        activity_method: apiMethods.POST,
        url: "/api/v1/masters/statuses/import",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Export,
        module: moduleTypes.Statuses,
        activity_name: activityName.exportStatus,
        activity_code: activityCode.exportStatus,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/statuses/export",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
    {
        activity_type: activityTypes.Log,
        module: moduleTypes.Statuses,
        activity_name: activityName.logStatus,
        activity_code: activityCode.logStatus,
        activity_method: apiMethods.GET,
        url: "/api/v1/masters/statuses/logs",
        status: true,
        form_params: [],
        search_params: [],
        access_params: {
        },
        control_params: [],
        payload_params: [],
        required_authentication: true,
      admin_access: true,
      user_access: false,
      employee_access: true,
      access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("employee")],
    },
];

export default statusesApiData;
