import { getRoleId } from "../../seeder-cookie";
import { activityTypes } from "../../../../utils/definitions/constants/activity-types";
import { IAPI } from "../../../../utils/interfaces/api.interface";
import { moduleTypes } from "../../../../utils/definitions/constants/modules";
import { activityCode, activityName } from "../../activities/user-wallet-activities";
import { apiMethods } from "../../../../utils/definitions/constants/api-methods";
import { datatypes } from "../../../../utils/definitions/constants/data-types";
import { defaultSearchParams } from "../../../../utils/helpers/seeder.helper";
import { searchTypes } from "../../../../utils/definitions/constants/search-types";

const userWalletApiData = (): IAPI[] => [
  // ─── WALLET & ACCOUNTS ──────────────────────────────────────────
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetWallet,
    activity_code: activityCode.GetWallet,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetAccounts,
    activity_code: activityCode.GetAccounts,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/accounts",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetAccountByCurrency,
    activity_code: activityCode.GetAccountByCurrency,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/accounts/:currency",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetBalance,
    activity_code: activityCode.GetBalance,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/balance",
    status: true,
    form_params: [],
    search_params: [
      {
        title: "currency",
        value: "currency",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
                is_required: false,
      },
    ],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },

  // ─── DEPOSITS ───────────────────────────────────────────────────
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Wallets,
    activity_name: activityName.CreateDeposit,
    activity_code: activityCode.CreateDeposit,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/deposits",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "amount_minor",
        value: "number",
        type: datatypes.Number,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "provider",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "idempotency_key",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "description",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetDeposit,
    activity_code: activityCode.GetDeposit,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/deposits/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },

  // ─── WITHDRAWALS ────────────────────────────────────────────────
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Wallets,
    activity_name: activityName.CreateWithdrawal,
    activity_code: activityCode.CreateWithdrawal,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/withdrawals",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "amount_minor",
        value: "number",
        type: datatypes.Number,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "provider",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "payout_destination",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "idempotency_key",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.ListWithdrawals,
    activity_code: activityCode.ListWithdrawals,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/withdrawals",
    status: true,
    form_params: [],
    search_params: [...defaultSearchParams],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetWithdrawal,
    activity_code: activityCode.GetWithdrawal,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/withdrawals/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.Wallets,
    activity_name: activityName.CancelWithdrawal,
    activity_code: activityCode.CancelWithdrawal,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/withdrawals/:id/cancel",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },

  // ─── HOLDS ──────────────────────────────────────────────────────
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Wallets,
    activity_name: activityName.CreateHold,
    activity_code: activityCode.CreateHold,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/holds",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "wallet_account_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "amount_minor",
        value: "number",
        type: datatypes.Number,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "reference_type",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "reference_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.ListHolds,
    activity_code: activityCode.ListHolds,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/holds",
    status: true,
    form_params: [],
    search_params: [
      {
        title: "status",
        value: "status",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
                is_required: false,
      },
    ],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetHold,
    activity_code: activityCode.GetHold,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/holds/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.Wallets,
    activity_name: activityName.ReleaseHold,
    activity_code: activityCode.ReleaseHold,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/holds/:id/release",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "reason",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Update,
    module: moduleTypes.Wallets,
    activity_name: activityName.CaptureHold,
    activity_code: activityCode.CaptureHold,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/holds/:id/capture",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "capture_amount_minor",
        value: "number",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "description",
        value: "string",
        type: datatypes.String,
        required: false,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },

  // ─── TRANSFERS ──────────────────────────────────────────────────
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Wallets,
    activity_name: activityName.CreateTransfer,
    activity_code: activityCode.CreateTransfer,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/transfers",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "to_user_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "amount_minor",
        value: "number",
        type: datatypes.Number,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "fee_minor",
        value: "number",
        type: datatypes.Number,
        required: false,
        parent: false,
        parent_key: "",
      },
      {
        key: "idempotency_key",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.ListTransfers,
    activity_code: activityCode.ListTransfers,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/transfers",
    status: true,
    form_params: [],
    search_params: [...defaultSearchParams],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetTransfer,
    activity_code: activityCode.GetTransfer,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/transfers/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },

  // ─── REFUNDS ────────────────────────────────────────────────────
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Wallets,
    activity_name: activityName.CreateRefund,
    activity_code: activityCode.CreateRefund,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/refunds",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "parent_transaction_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "amount_minor",
        value: "number",
        type: datatypes.Number,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "idempotency_key",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.ListRefunds,
    activity_code: activityCode.ListRefunds,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/refunds",
    status: true,
    form_params: [],
    search_params: [...defaultSearchParams],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetRefund,
    activity_code: activityCode.GetRefund,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/refunds/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },

  // ─── REVERSALS ──────────────────────────────────────────────────
  {
    activity_type: activityTypes.Create,
    module: moduleTypes.Wallets,
    activity_name: activityName.CreateReversal,
    activity_code: activityCode.CreateReversal,
    activity_method: apiMethods.POST,
    url: "/api/v1/wallets/reversals",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [
      {
        key: "parent_transaction_id",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "amount_minor",
        value: "number",
        type: datatypes.Number,
        required: true,
        parent: false,
        parent_key: "",
      },
      {
        key: "currency",
        value: "string",
        type: datatypes.String,
        required: true,
        parent: false,
        parent_key: "",
      },
    ],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.ListReversals,
    activity_code: activityCode.ListReversals,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/reversals",
    status: true,
    form_params: [],
    search_params: [...defaultSearchParams],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetReversal,
    activity_code: activityCode.GetReversal,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/reversals/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },

  // ─── TRANSACTIONS & LEDGER ──────────────────────────────────────
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.ListTransactions,
    activity_code: activityCode.ListTransactions,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/transactions",
    status: true,
    form_params: [],
    search_params: [
      ...defaultSearchParams,
      {
        title: "wallet_id",
        value: "wallet_id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
                is_required: false,
      },
      {
        title: "type",
        value: "type",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
                is_required: false,
      },
      {
        title: "status",
        value: "status",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
                is_required: false,
      },
      {
        title: "currency",
        value: "currency",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
                is_required: false,
      },
    ],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.Show,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetTransaction,
    activity_code: activityCode.GetTransaction,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/transactions/:id",
    status: true,
    form_params: [],
    search_params: [],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
  {
    activity_type: activityTypes.List,
    module: moduleTypes.Wallets,
    activity_name: activityName.GetLedger,
    activity_code: activityCode.GetLedger,
    activity_method: apiMethods.GET,
    url: "/api/v1/wallets/ledger",
    status: true,
    form_params: [],
    search_params: [
      ...defaultSearchParams,
      {
        title: "account_id",
        value: "account_id",
        allowed_values: [],
        datatype: datatypes.String,
        search_type: searchTypes.Exact,
        is_active: true,
                is_required: false,
      },
    ],
        access_params: {},
    control_params: [],
    payload_params: [],
    required_authentication: true,
    access_roles: [getRoleId("super_admin"), getRoleId("admin"), getRoleId("user")],
  },
];

export default userWalletApiData;
