export enum moduleTypes {
  Authentication = "authentication",
  Statuses = "statuses",
  Roles = "roles",
  Users = "users",
  Countries = "countries",
  Providers = "providers",
  Uploads = "uploads",
  Jobs = "jobs",
  Applications = "applications",
  Notifications = "notifications",
  Regions = "regions",
  Districts = "districts",
  AuthenticationSession = "authentication_session",
  Services = "services",
  Declaimers = "declaimers",
  Priorities = "priorities",
  Suburbs = "suburbs",
  Units = "units",
  ServiceCountryConfigurations = "service_country_configurations",
  ServiceAreaConfigurations = "service_area_configurations",
  ServiceUserConfigurations = "service_user_configurations",
  ServiceUserDocumentConfigurations = "service_user_document_configurations",
  ServiceDocuments = "service_documents",
  ServiceDocumentConfigurations = "service_document_configurations",
  DocumentTypes = "document_types",
  Currencies = "currencies",
  Wallets = "wallets",
  Carousels = "carousels",
}

